version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge